### ISSUE TITLE
Bug: Chrome/Edge document loading but not showing

### ISSUE THREAD

**Issue by AndTmf** [DanielArnould/react-pdf-highlighter#22]
Hello, I have tested everything with Firefox so far and it works without any problems. 

After testing with Edge and Chrome, there is often the problem that the PDF is loaded to 100% but then not displayed. Like on the screenshot. After several reloads of the page it works eventually. There are no messages in the console. 

I will provide more information when I have found out where it comes from. 

![grafik](https://github.com/user-attachments/assets/58df0bcc-0167-440e-a0fa-1cf1eaa3933f)

**Comment by DanielArnould** [comment]
Hey, 
Would you be able to share the PDF document? Either way, try loading it with the PDF.js [demo viewer](https://mozilla.github.io/pdf.js/web/viewer.html) to see if it's an issue with this library.

**Comment by AndTmf** [comment]
Thanks for the idea with the pdf.js demo!

I did some tests and the pdf.js demo as well as the example implementation have no problems with Chromium. Maybe it is a Next.js problem. Definitely a problem in my implementation on my side. Not a general bug, was a bit hasty.

**Comment by DanielArnould** [comment]
Closed due to inactivity
