### ISSUE TITLE
Error loading PDF document: The API version "4.5.136" does not match the Worker version "4.4.168".!

### ISSUE THREAD

**Issue by tunganhh239** [DanielArnould/react-pdf-highlighter#29]
I just installed the library, but the worker version might be outdated. Please update it. Thanks.

**Comment by tunganhh239** [comment]
Just remove the ^ of pdfjs-dist in package.json

**Comment by luisoos** [comment]
# [Next.js / T3 Stack]

If the above solution doesn't fix the problem, try this:

### Yarn

```json 
    // Add this to package.json
    "resolutions": {
        "pdfjs-dist": "4.4.168"
    }
```

### NPM

```json
    // Add this to package.json
        "overrides": {
            "pdfjs-dist": "4.4.168"
        }
```

or specific for this package:

```json
    // Add this to package.json
        "overrides": {
            "react-pdf-highlighter-extended": {
                "pdfjs-dist": "4.4.168"
            }
        }
```

**It did not work for me at first, I had to yarn update, install etc. some times, but maybe that was just in my case...**
